# Generated by Django 5.2.4 on 2025-08-28 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEstrategica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('sigla', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FuenteInformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AreaOrganizacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=180)),
                ('responsable', models.CharField(blank=True, max_length=120)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='cis.entidad')),
            ],
            options={
                'verbose_name': 'Área organizacional',
                'verbose_name_plural': 'Áreas organizacionales',
            },
        ),
        migrations.CreateModel(
            name='ObjetivoEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('descripcion', models.TextField()),
                ('area_estrategica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivos', to='cis.areaestrategica')),
                ('area_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='cis.areaorganizacional')),
            ],
            options={
                'verbose_name': 'Objetivo estratégico',
            },
        ),
        migrations.CreateModel(
            name='AccionEstrategica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('descripcion', models.TextField()),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='cis.objetivoestrategico')),
            ],
            options={
                'verbose_name': 'Acción estratégica (producto)',
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('descripcion', models.TextField()),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='cis.accionestrategica')),
            ],
            options={
                'verbose_name': 'Operación',
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(blank=True, max_length=30)),
                ('nombre', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('RESULTADO_PDES', 'Resultado PDES'), ('GESTION', 'Gestión'), ('EFICACIA', 'Eficacia'), ('EFICIENCIA', 'Eficiencia'), ('CALIDAD', 'Calidad'), ('COBERTURA', 'Cobertura'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('unidad', models.CharField(choices=[('NRO', 'Número'), ('PCT', 'Porcentaje'), ('TXT', 'Texto')], default='NRO', max_length=3)),
                ('formula_texto', models.TextField(blank=True)),
                ('anio_linea_base', models.PositiveSmallIntegerField(default=2020)),
                ('linea_base', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('anio_meta', models.PositiveSmallIntegerField(default=2025)),
                ('meta_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fuentes', models.ManyToManyField(blank=True, related_name='indicadores', to='cis.fuenteinformacion')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='cis.operacion')),
            ],
            options={
                'verbose_name': 'Indicador',
            },
        ),
        migrations.CreateModel(
            name='SerieIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('anio', models.PositiveSmallIntegerField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('es_programado', models.BooleanField(default=True)),
                ('nota', models.CharField(blank=True, max_length=250)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='cis.indicador')),
            ],
            options={
                'verbose_name': 'Serie anual de indicador',
                'ordering': ['indicador', 'anio'],
            },
        ),
        migrations.AddIndex(
            model_name='areaorganizacional',
            index=models.Index(fields=['entidad', 'nombre'], name='cis_areaorg_entidad_34c953_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='areaorganizacional',
            unique_together={('entidad', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='objetivoestrategico',
            index=models.Index(fields=['area_org', 'codigo'], name='cis_objetiv_area_or_c5ee0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='objetivoestrategico',
            unique_together={('area_org', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='accionestrategica',
            index=models.Index(fields=['objetivo', 'codigo'], name='cis_accione_objetiv_8c1dd0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accionestrategica',
            unique_together={('objetivo', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='operacion',
            index=models.Index(fields=['accion', 'codigo'], name='cis_operaci_accion__a5e537_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='operacion',
            unique_together={('accion', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='indicador',
            index=models.Index(fields=['operacion', 'nombre'], name='cis_indicad_operaci_95a8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='indicador',
            index=models.Index(fields=['tipo', 'unidad'], name='cis_indicad_tipo_b8e451_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='indicador',
            unique_together={('operacion', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='serieindicador',
            index=models.Index(fields=['indicador', 'anio'], name='cis_seriein_indicad_d7ff11_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serieindicador',
            unique_together={('indicador', 'anio', 'es_programado')},
        ),
    ]
